
<CategoryScreen>:
    BoxLayout:
        orientation: "vertical"
        spacing: 0
        padding: 0

        # Top Bar
        TopBar:
                
               
              
        # Header Section 
        BoxLayout:                  
            size_hint_y: None
            height: 40
            padding: [15, 0, 15, 0]
            canvas.before:
                Color:
                    rgba: 0,0,0,0
                Rectangle:
                    pos: self.pos
                    size: self.size

            Label:
                text: "Expenses Category"
                font_size: 14
                bold: True
                halign: "left"
                valign: "middle"
                color: app.get_color_from_hex("#000000")
                text_size: self.width, None
            BoxLayout:
                size_hint_x: 1
                width: 20
                spacing: 10
                padding: [10, 0, 0, 0]
                background_color: 0,0,0,1
                canvas.before:
                    Color:
                        rgba: app.get_color_from_hex("#E0E0E0")
                    RoundedRectangle:
                        pos: self.pos
                        size: self.size
                        radius: [8]
                    Line:
                        rectangle: self.x, self.y, self.width, self.height
                        width: 1

                Image:
                    source: "assets/search.png"
                    size_hint: None, None
                    size: 20, 20
                    pos_hint: {"center_x": 0.5, "center_y": 0.5}
                    allow_stretch: True
                TextInput:
                    id: search_input
                    text: ''
                    size_hint_x: 1
                    hint_text: 'Search'
                    background_color: 0,0,0,0
                    foreground_color: app.get_color_from_hex("#000000")
                    background_normal: ''
                    background_active: ''
                    padding_y: [self.height / 2 - self.line_height / 2]
                    on_text: root.on_search_text(self, self.text)
        
        # Main Content Area (ScrollView)
        ScrollView:
            do_scroll_x: False
            do_scroll_y: True
            BoxLayout:
                orientation: 'vertical'
                spacing: 15
                padding: [15, 15, 15, 15]
                size_hint_y: None
                height: self.minimum_height
                
                # Personal Section
                Button:
                    text: 'Personal'
                    background_normal: ''
                    background_color: 0,0,0,0
                    background_down: ''
                    color: app.get_color_from_hex("#000000")    
                    font_size: 14
                    bold: True
                    size_hint_y: None
                    size_hint_x: None
                    height: 30
                    width: 90
                    on_release: root.filter_personal()
                
                # Personal Categories ScrollView
                ScrollView:
                    id: category_scroll
                    do_scroll_x: True
                    do_scroll_y: False
                    size_hint_y: None
                    height: 140

                    BoxLayout:
                        orientation:'horizontal'
                        size_hint_x: None
                        size_hint_y: None
                        width: self.minimum_width
                        height: 140
                        padding: [0, 0, 15, 0]
                        spacing: 15
                
                # Bills Section
                BoxLayout:   
                    size_hint_y: None
                    size_hint_x: 1
                    orientation: 'horizontal'
                    spacing: 10
                    height: 30
                    
                    Button:
                        text: 'Bills'
                        background_normal: ''
                        background_color: 0,0,0,0
                        background_down: ''
                        color: app.get_color_from_hex("#000000")    
                        font_size: 14
                        bold: True
                        size_hint_y: None
                        size_hint_x: None
                        height: 30
                        width: 90
                        on_release: root.filter_bills()
                    
                    Widget:
                        size_hint_x: 1
                    
                    Button:
                        size_hint_x: None
                        size_hint_y: None
                        width: 30
                        height: 30
                        background_color: 0, 0, 0, 0
                        on_release:
                            print("Scroll right clicked")
                        Image:
                            source: "assets/right-arrow.png"
                            center_x: self.parent.center_x 
                            center_y: self.parent.center_y
                            size_hint: None, None
                            size: 20, 20

                # Bills Categories ScrollView
                ScrollView:
                    id: bills_scroll
                    do_scroll_x: True
                    do_scroll_y: False
                    size_hint_y: None
                    height: 140
                    
                    BoxLayout:
                        orientation:'horizontal'
                        size_hint_x: None
                        size_hint_y: None
                        width: self.minimum_width
                        height: 140
                        padding: [0, 0, 15, 0]
                        spacing: 15
                    
        # Bottom Navigation Bar
        BottomNavBar:
